### ISSUE TITLE
How to get the paper?

### ISSUE THREAD

**Issue by dotaball** [Dootmaan/PFSeg#1]
Hi Dootmaan , thank you for making the code public, but where can I get this paper?

**Comment by Dootmaan** [comment]
> Hi Dootmaan , thank you for making the code public, but where can I get this paper?

Thank you for your interest in our work. MICCAI 2021 will be held from September 27th to October 1st as a virtual event. Our paper will then be published along with other papers on the book of MICCAI 2021 (probably in part4). MICCAI committee recommended us not submitting the paper to arXiv so im sorry currently you have to wait for the final publlication.
